name: bewr_home
description: Bewr Home is an open-source and multi-platform smart home application that stands out by proactively suggesting ways to improve your smart home and make your connected objects smarter.

publish_to: "none"

version: 0.0.8 # Accessibility v1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_shake_animated: ^0.0.5
  go_router: ^6.0.6
  google_fonts: ^4.0.3
  intl: ^0.17.0
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.17
  url_strategy: ^0.2.0

dev_dependencies:
  analyzer: ^5.4.0
  firebase_crashlytics: ^3.0.11
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  plausible_analytics: ^0.2.1
  test: ^1.22.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#800020"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  generate: true
